# Generated by Django 4.0 on 2021-12-18 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory', models.CharField(max_length=5)),
                ('hero', models.CharField(max_length=20)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privateApp.match')),
            ],
        ),
    ]
