# Generated by Django 4.0 on 2021-12-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='matchId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='sequenceNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='deaths',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='kills',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
