# Generated by Django 4.0 on 2021-12-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateApp', '0002_match_end_time_match_matchid_match_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='end_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='rank',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='sequenceNum',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='deaths',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='kills',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.BigIntegerField(),
        ),
    ]
