# Generated by Django 4.0 on 2021-12-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateApp', '0004_alter_match_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hero',
            field=models.CharField(max_length=30),
        ),
    ]
