# Generated by Django 4.0 on 2021-12-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateApp', '0005_alter_player_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.AlterField(
            model_name='match',
            name='matchId',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
