# Generated by Django 4.0 on 2021-12-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateApp', '0006_remove_match_id_alter_match_matchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='lobby_type',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
