# Generated by Django 4.0 on 2022-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateApp', '0008_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='lobby_type',
            field=models.CharField(max_length=30),
        ),
    ]
